export const mainConfig = {
    "burkinafaso": {
        "Name": "Burkina Faso",
        "TLC": "BFA",
        "Prefix": "BFA",
        "Adm1": "Region",
        "Adm2": "Province",
        "Center": [12.7, -1.8],
        "Zoom": [6],
        "DistrictOnly": [],
        "NoR1": [],
        "NoR2": [],
        "indicators": {
            "LBW": {
                "Indicator":"Low birth weight",
                "Theme":"Child Health",
                "Remark":"",
                "Min":0.0,
                "Max":42.5,
                "Delta":2.5,
                "CHMin":-25.0,
                "CHMax":25.0,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "Min_diet": {
                "Indicator":"Minimum acceptable diet",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":48.0,
                "Delta":3.0,
                "CHMin":-32.0,
                "CHMax":24.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "Sever_wast": {
                "Indicator":"Prevalence of severe wasting",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":42.5,
                "Delta":2.5,
                "CHMin":-22.5,
                "CHMax":25.0,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "Teen_Pregn": {
                "Indicator":"Teenage pregnancies",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":40.0,
                "Delta":2.5,
                "CHMin":-27.5,
                "CHMax":17.5,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "U_Pregn": {
                "Indicator":"Unwanted births",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":40.0,
                "Delta":2.5,
                "CHMin":-27.5,
                "CHMax":17.5,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "Anaemia": {
                "Indicator":"Prevalence of anaemia ",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":15.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-35.0,
                "CHMax":45.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "ANC_4plus": {
                "Indicator":"Antenatal care (4+ visits)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "ANC_blood": {
                "Indicator":"Antenatal care (blood screening)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":30.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-15.0,
                "CHMax":55.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "ANC_suppl": {
                "Indicator":"Antenatal care (supplements)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "ANC_timing": {
                "Indicator":"Antenatal care (timing)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-30.0,
                "CHMax":70.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "ANC_urine": {
                "Indicator":"Antenatal care (urine screening)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "Breastfeed": {
                "Indicator":"Exclusive breastfeeding",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":20.0,
                "Max":90.0,
                "Delta":5.0,
                "CHMin":-25.0,
                "CHMax":75.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "C_Prev": {
                "Indicator":"Modern contraceptive use",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":4.0,
                "Max":72.0,
                "Delta":4.0,
                "CHMin":-20.0,
                "CHMax":52.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "Child_m": {
                "Indicator":"Child marriage",
                "Theme":"Child Protection",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "Labour_fem": {
                "Indicator":"Female labour force participation",
                "Theme":"Livelihoods",
                "Remark":"",
                "Min":4.0,
                "Max":84.0,
                "Delta":4.0,
                "CHMin":-24.0,
                "CHMax":44.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "NAR_prim": {
                "Indicator":"Net primary school attendance rate",
                "Theme":"Education",
                "Remark":"",
                "Min":62.0,
                "Max":98.0,
                "Delta":2.0,
                "CHMin":-80.0,
                "CHMax":32.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "NAR_sec": {
                "Indicator":"Net secondary school attendance rate",
                "Theme":"Education",
                "Remark":"",
                "Min":28.0,
                "Max":96.0,
                "Delta":4.0,
                "CHMin":-20.0,
                "CHMax":32.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "Stunting": {
                "Indicator":"Prevalence of stunting",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "Wash_sanit": {
                "Indicator":"WASH coverage (sanitation)",
                "Theme":"WASH",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-60.0,
                "CHMax":90.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "Wash_water": {
                "Indicator":"WASH coverage (water)",
                "Theme":"WASH",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-80.0,
                "CHMax":80.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "NMR": {
                "Indicator":"Neonatal mortality rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":50,
                "Delta":2.5,
                "CHMin":-25,
                "CHMax":25,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "Unsafe_Ab": {
                "Indicator":"Unsafe abortions ",
                "Theme":"Reproductive Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":60,
                "Delta":3,
                "CHMin":-30,
                "CHMax":30,
                "CHDelta":3,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "CHMR": {
                "Indicator":"Child mortality rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":20,
                "Delta":1,
                "CHMin":-10.0,
                "CHMax":10.0,
                "CHDelta":1,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
            "Lab_child": {
                "Indicator":"Prevalence of child workers",
                "Theme":"Child Protection",
                "Remark":"For child worker, census estimates were used to calculate the indicator, and only had one point in time was available.",
                "Min":0.0,
                "Max":10.0,
                "Delta":0.05,
                "CHMin":-5.0,
                "CHMax":5.0,
                "CHDelta":-0.05,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"Census",
                "R2":"No data",
                "Y1":"2011",
                "Y2":null
            },
            "Stillbirth": {
                "Indicator":"Still birth rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":2.0,
                "Max":40.0,
                "Delta":2.0,
                "CHMin":-20.0,
                "CHMax":20.0,
                "CHDelta":2.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2019-21"
            },
        }
    },
    "india": {
        "Name": "India",
        "TLC": "IND",
        "Prefix": "",
        "N1": 36,
        "N2": 742,
        "Adm1": "State",
        "Adm2": "District",
        "Center": [22.9, 79.6],
        "Zoom": [4],
        "DistrictOnly": ['NMR', 'Unsafe_Ab', 'CHMR', 'Lab_child', 'Stillbirth'],
        "NoR1": [],
        "NoR2": ['Lab_child'],
        "indicators": {
            "LBW": {
                "Indicator":"Low birth weight",
                "Theme":"Child Health",
                "Remark":"",
                "Min":0.0,
                "Max":42.5,
                "Delta":2.5,
                "CHMin":-25.0,
                "CHMax":25.0,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Min_diet": {
                "Indicator":"Minimum acceptable diet",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":48.0,
                "Delta":3.0,
                "CHMin":-32.0,
                "CHMax":24.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Sever_wast": {
                "Indicator":"Prevalence of severe wasting",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":42.5,
                "Delta":2.5,
                "CHMin":-22.5,
                "CHMax":25.0,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Teen_Pregn": {
                "Indicator":"Teenage pregnancies",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":40.0,
                "Delta":2.5,
                "CHMin":-27.5,
                "CHMax":17.5,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "U_Pregn": {
                "Indicator":"Unwanted births",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":40.0,
                "Delta":2.5,
                "CHMin":-27.5,
                "CHMax":17.5,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Anaemia": {
                "Indicator":"Prevalence of anaemia ",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":15.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-35.0,
                "CHMax":45.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_4plus": {
                "Indicator":"Antenatal care (4+ visits)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_blood": {
                "Indicator":"Antenatal care (blood screening)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":30.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-15.0,
                "CHMax":55.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_suppl": {
                "Indicator":"Antenatal care (supplements)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_timing": {
                "Indicator":"Antenatal care (timing)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-30.0,
                "CHMax":70.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "ANC_urine": {
                "Indicator":"Antenatal care (urine screening)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Breastfeed": {
                "Indicator":"Exclusive breastfeeding",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":20.0,
                "Max":90.0,
                "Delta":5.0,
                "CHMin":-25.0,
                "CHMax":75.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "C_Prev": {
                "Indicator":"Modern contraceptive use",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":4.0,
                "Max":72.0,
                "Delta":4.0,
                "CHMin":-20.0,
                "CHMax":52.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Child_m": {
                "Indicator":"Child marriage",
                "Theme":"Child Protection",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Labour_fem": {
                "Indicator":"Female labour force participation",
                "Theme":"Livelihoods",
                "Remark":"",
                "Min":4.0,
                "Max":84.0,
                "Delta":4.0,
                "CHMin":-24.0,
                "CHMax":44.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "NAR_prim": {
                "Indicator":"Net primary school attendance rate",
                "Theme":"Education",
                "Remark":"",
                "Min":62.0,
                "Max":98.0,
                "Delta":2.0,
                "CHMin":-80.0,
                "CHMax":32.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "NAR_sec": {
                "Indicator":"Net secondary school attendance rate",
                "Theme":"Education",
                "Remark":"",
                "Min":28.0,
                "Max":96.0,
                "Delta":4.0,
                "CHMin":-20.0,
                "CHMax":32.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Stunting": {
                "Indicator":"Prevalence of stunting",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Wash_sanit": {
                "Indicator":"WASH coverage (sanitation)",
                "Theme":"WASH",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-60.0,
                "CHMax":90.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Wash_water": {
                "Indicator":"WASH coverage (water)",
                "Theme":"WASH",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-80.0,
                "CHMax":80.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "NMR": {
                "Indicator":"Neonatal mortality rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":50,
                "Delta":2.5,
                "CHMin":-25,
                "CHMax":25,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Unsafe_Ab": {
                "Indicator":"Unsafe abortions ",
                "Theme":"Reproductive Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":60,
                "Delta":3,
                "CHMin":-30,
                "CHMax":30,
                "CHDelta":3,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "CHMR": {
                "Indicator":"Child mortality rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":20,
                "Delta":1,
                "CHMin":-10.0,
                "CHMax":10.0,
                "CHDelta":1,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
            "Lab_child": {
                "Indicator":"Prevalence of child workers",
                "Theme":"Child Protection",
                "Remark":"Child age in India is between 5-17. For child worker, census estimates were used to calculate the indicator, and only had one point in time.",
                "Min":0.0,
                "Max":10.0,
                "Delta":0.05,
                "CHMin":-5.0,
                "CHMax":5.0,
                "CHDelta":-0.05,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"Census",
                "R2":"No data",
                "Y1":"2011",
                "Y2":null
            },
            "Stillbirth": {
                "Indicator":"Still birth rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":2.0,
                "Max":40.0,
                "Delta":2.0,
                "CHMin":-20.0,
                "CHMax":20.0,
                "CHDelta":2.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2015-16",
                "Y2":"2019-21"
            },
        }
    },
    "kenya": {
        "Name": "Kenya",
        "TLC": "KEN",
        "Prefix": "KEN_",
        "N1": 47,
        "N2": 335,
        "Adm1": "County",
        "Adm2": "Sub-county",
        "Center": [0.6, 37.5],
        "Zoom": [6],
        "DistrictOnly": ['U5', 'NMR', 'NTDs_fil', 'NTDs_oncho', 'LBW', 'Stillbirth', 'Lab_child'],
        "NoR1": ['Lab_child'],
        "NoR2": [],
        "indicators": {
            "LBW": {
                "Indicator":"Low birth weight",
                "Theme":"Child Health",
                "Remark":"Only county-level estimate is available",
                "Min":0.0,
                "Max":30.0,
                "Delta":2.5,
                "CHMin":-15.0,
                "CHMax":15.0,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Min_diet": {
                "Indicator":"Minimum acceptable diet",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":72.0,
                "Delta":4.0,
                "CHMin":-45.0,
                "CHMax":45.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Teen_Pregn": {
                "Indicator":"Teenage pregnancies",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5,
                "CHMin":-20.0,
                "CHMax":56.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "U_Pregn": {
                "Indicator":"Unwanted births",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5,
                "CHMin":-30.0,
                "CHMax":84.0,
                "CHDelta":6,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "ANC_4plus": {
                "Indicator":"Antenatal care (4+ visits)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":90.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "ANC_blood": {
                "Indicator":"Antenatal care (blood screening)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":90.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "ANC_suppl": {
                "Indicator":"Antenatal care (supplements)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":90.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "ANC_timing": {
                "Indicator":"Antenatal care (timing)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":51.0,
                "Delta":3.0,
                "CHMin":-6.0,
                "CHMax":30.0,
                "CHDelta":2.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "ANC_urine": {
                "Indicator":"Antenatal care (urine screening)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":90.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Breastfeed": {
                "Indicator":"Exclusive breastfeeding",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":15.0,
                "Max":80.0,
                "Delta":5.0,
                "CHMin":-60.0,
                "CHMax":30.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "C_Prev": {
                "Indicator":"Modern contraceptive use",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":15.0,
                "Max":90.0,
                "Delta":5.0,
                "CHMin":-35.0,
                "CHMax":60.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Child_m": {
                "Indicator":"Child marriage",
                "Theme":"Child Protection",
                "Remark":"",
                "Min":0.0,
                "Max":76.0,
                "Delta":4.0,
                "CHMin":-25.0,
                "CHMax":50.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Labour_fem": {
                "Indicator":"Female labour force participation",
                "Theme":"Livelihoods",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-64.0,
                "CHMax":64.0,
                "CHDelta":8.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "NAR_prim": {
                "Indicator":"Net primary school attendance rate",
                "Theme":"Education",
                "Remark":"",
                "Min":0.0,
                "Max":76.0,
                "Delta":4.0,
                "CHMin":-60.0,
                "CHMax":40.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "NAR_sec": {
                "Indicator":"Net secondary school attendance rate",
                "Theme":"Education",
                "Remark":"",
                "Min":0.0,
                "Max":76.0,
                "Delta":4.0,
                "CHMin":-60.0,
                "CHMax":40.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Stunting": {
                "Indicator":"Prevalence of stunting",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":76.0,
                "Delta":4.0,
                "CHMin":-27.0,
                "CHMax":18.0,
                "CHDelta":3.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Wasting": {
                "Indicator":"Prevalence of wasting",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":64.0,
                "Delta":4.0,
                "CHMin":-16.0,
                "CHMax":20.0,
                "CHDelta":2.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Wash_sanit": {
                "Indicator":"WASH coverage (sanitation)",
                "Theme":"WASH",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-90.0,
                "CHMax":90.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Wash_water": {
                "Indicator":"WASH coverage (water)",
                "Theme":"WASH",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-90.0,
                "CHMax":90.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "NMR": {
                "Indicator":"Neonatal mortality rate",
                "Theme":"Child Health",
                "Remark":"",
                "Min":10,
                "Max":30,
                "Delta":2.5,
                "CHMin":-4,
                "CHMax":0,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"IHME",
                "R2":"IHME",
                "Y1":"2014",
                "Y2":"2017"
            },
            "U5": {
                "Indicator":"Under five mortality rate",
                "Theme":"Child Health",
                "Remark":"",
                "Min":20,
                "Max":100,
                "Delta":1,
                "CHMin":-10.0,
                "CHMax":10.0,
                "CHDelta":1,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"IHME",
                "R2":"IHME",
                "Y1":"2014",
                "Y2":"2017"
            },
            "Lab_child": {
                "Indicator":"Prevalence of child workers",
                "Theme":"Child Protection",
                "Remark":"Child age in Kenya is between 5-17. Only county-level estimate is available.",
                "Min":0.0,
                "Max":40.0,
                "Delta":0.05,
                "CHMin":-20.0,
                "CHMax":20.0,
                "CHDelta":-0.05,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"",
                "R2":"Census",
                "Y1":null,
                "Y2":"2019"
            },
            "Stillbirth": {
                "Indicator":"Still birth rate",
                "Theme":"Child Health",
                "Remark":"Only county-level estimate is available.",
                "Min":0.0,
                "Max":80.0,
                "Delta":2.0,
                "CHMin":-60.0,
                "CHMax":60.0,
                "CHDelta":2.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"County",
                "R1":"DHS-7",
                "R2":"DHS-8",
                "Y1":"2014",
                "Y2":"2022"
            },
            "NTDs_fil": {
                "Indicator":"NTDs: Lymphatic filariasis",
                "Theme":"Neglected Tropical Diseases",
                "Remark":"",
                "Min":0.0,
                "Max":0.1,
                "Delta":0.002,
                "CHMin":-0.03,
                "CHMax":0.03,
                "CHDelta":0.002,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"IHME",
                "R2":"IHME",
                "Y1":"2014",
                "Y2":"2018"
            },
            "NTDs_oncho": {
                "Indicator":"NTDs: Onchocerciasis",
                "Theme":"Neglected Tropical Diseases",
                "Remark":"",
                "Min":0.0,
                "Max":0.04,
                "Delta":0.002,
                "CHMin":-0.02,
                "CHMax":0.02,
                "CHDelta":0.002,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"IHME",
                "R2":"IHME",
                "Y1":"2014",
                "Y2":"2018"
            }
        }
    },
    "nigeria": {
        "Name": "Nigeria",
        "TLC": "NGA",
        "Prefix": "NGA",
        "Adm1": "State",
        "Adm2": "Local Government Area",
        "Center": [9.5, 8.0],
        "Zoom": [6],
        "DistrictOnly": [],
        "NoR1": [],
        "NoR2": [],
        "indicators": {
            "LBW": {
                "Indicator":"Low birth weight",
                "Theme":"Child Health",
                "Remark":"",
                "Min":0.0,
                "Max":42.5,
                "Delta":2.5,
                "CHMin":-25.0,
                "CHMax":25.0,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Min_diet": {
                "Indicator":"Minimum acceptable diet",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":48.0,
                "Delta":3.0,
                "CHMin":-32.0,
                "CHMax":24.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Sever_wast": {
                "Indicator":"Prevalence of severe wasting",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":42.5,
                "Delta":2.5,
                "CHMin":-22.5,
                "CHMax":25.0,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Teen_Pregn": {
                "Indicator":"Teenage pregnancies",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":40.0,
                "Delta":2.5,
                "CHMin":-27.5,
                "CHMax":17.5,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "U_Pregn": {
                "Indicator":"Unwanted births",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":40.0,
                "Delta":2.5,
                "CHMin":-27.5,
                "CHMax":17.5,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Anaemia": {
                "Indicator":"Prevalence of anaemia ",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":15.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-35.0,
                "CHMax":45.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "ANC_4plus": {
                "Indicator":"Antenatal care (4+ visits)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "ANC_blood": {
                "Indicator":"Antenatal care (blood screening)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":30.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-15.0,
                "CHMax":55.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "ANC_suppl": {
                "Indicator":"Antenatal care (supplements)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "ANC_timing": {
                "Indicator":"Antenatal care (timing)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-30.0,
                "CHMax":70.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "ANC_urine": {
                "Indicator":"Antenatal care (urine screening)",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Breastfeed": {
                "Indicator":"Exclusive breastfeeding",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":20.0,
                "Max":90.0,
                "Delta":5.0,
                "CHMin":-25.0,
                "CHMax":75.0,
                "CHDelta":5.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "C_Prev": {
                "Indicator":"Modern contraceptive use",
                "Theme":"Reproductive Health",
                "Remark":"",
                "Min":4.0,
                "Max":72.0,
                "Delta":4.0,
                "CHMin":-20.0,
                "CHMax":52.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Child_m": {
                "Indicator":"Child marriage",
                "Theme":"Child Protection",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Labour_fem": {
                "Indicator":"Female labour force participation",
                "Theme":"Livelihoods",
                "Remark":"",
                "Min":4.0,
                "Max":84.0,
                "Delta":4.0,
                "CHMin":-24.0,
                "CHMax":44.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "NAR_prim": {
                "Indicator":"Net primary school attendace",
                "Theme":"Education",
                "Remark":"",
                "Min":62.0,
                "Max":98.0,
                "Delta":2.0,
                "CHMin":-80.0,
                "CHMax":32.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "NAR_sec": {
                "Indicator":"Net secondary school attendance rate",
                "Theme":"Education",
                "Remark":"",
                "Min":28.0,
                "Max":96.0,
                "Delta":4.0,
                "CHMin":-20.0,
                "CHMax":32.0,
                "CHDelta":4.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Stunting": {
                "Indicator":"Prevalence of stunting",
                "Theme":"Nutrition",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-70.0,
                "CHMax":70.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Wash_sanit": {
                "Indicator":"WASH coverage (sanitation)",
                "Theme":"WASH",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-60.0,
                "CHMax":90.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Wash_water": {
                "Indicator":"WASH coverage (water)",
                "Theme":"WASH",
                "Remark":"",
                "Min":0.0,
                "Max":100.0,
                "Delta":5.0,
                "CHMin":-80.0,
                "CHMax":80.0,
                "CHDelta":10.0,
                "Palette1":"CIFF20_r",
                "Palette2":"CIFF20_r",
                "Resolution":"5 km",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "NMR": {
                "Indicator":"Neonatal mortality rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":50,
                "Delta":2.5,
                "CHMin":-25,
                "CHMax":25,
                "CHDelta":2.5,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Unsafe_Ab": {
                "Indicator":"Unsafe abortions ",
                "Theme":"Reproductive Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":60,
                "Delta":3,
                "CHMin":-30,
                "CHMax":30,
                "CHDelta":3,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "CHMR": {
                "Indicator":"Child mortality rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":0,
                "Max":20,
                "Delta":1,
                "CHMin":-10.0,
                "CHMax":10.0,
                "CHDelta":1,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
            "Lab_child": {
                "Indicator":"Prevalence of child workers",
                "Theme":"Child Protection",
                "Remark":"For child worker, census estimates were used to calculate the indicator, and only had one point in time was available.",
                "Min":0.0,
                "Max":10.0,
                "Delta":0.05,
                "CHMin":-5.0,
                "CHMax":5.0,
                "CHDelta":-0.05,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"Census",
                "R2":"No data",
                "Y1":"2011",
                "Y2":null
            },
            "Stillbirth": {
                "Indicator":"Still birth rate",
                "Theme":"Child Health",
                "Remark":"For this indicator, district estimates only were produced. The indicators shown here are rare events, highlighting the necessity for cautious interpretation and utilization of findings, given the limited district-level sample sizes.",
                "Min":2.0,
                "Max":40.0,
                "Delta":2.0,
                "CHMin":-20.0,
                "CHMax":20.0,
                "CHDelta":2.0,
                "Palette1":"CIFF20",
                "Palette2":"CIFF20",
                "Resolution":"District",
                "R1":"NFHS-4",
                "R2":"NFHS-5",
                "Y1":"2014",
                "Y2":"2022"
            },
        }
    }
}

export const indicatorDef = {
    "LBW": {
        "Indicator": "Low birth weight",
        "Theme": "Child health",
        "Definition": "Percentage (%) of live births in the 5 years preceding the survey weighed at birth reported as less than 2.5 kg",
        "Unit": "per cent",
        "Denominator": "live births in the five (or three) years preceding the survey with a reported birth weight",
        "Statement": "of live births weighed less than 2.5 kg at birth",
        "Proportional": false,
    },
    "Min_diet": {
        "Indicator": "Minimum acceptable diet",
        "Theme": "Nutrition",
        "Definition": "Percentage (%) of children aged 6 to 23 months who had at least minimum meal frequency and minimum diversified diet during the previous day",
        "Unit": "per cent",
        "Denominator": "children aged 6 to 23 months",
        "Statement": "of children aged 6 to 23 months had at least minimum meal frequency and minimum diversified diet during the previous day",
        "Proportional": true,
    },
    "Sever_wast": {
        "Indicator": "Prevalence of severe wasting",
        "Theme": "Nutrition",
        "Definition": "Percentage (%) of children wasted (below -3 SD of weight for height according to the WHO\u2019s standard)",
        "Unit": "per cent",
        "Denominator": "children under age five",
        "Statement": "of children under age five were wasted",
        "Proportional": false,
    },
    "Teen_Pregn": {
        "Indicator": "Teenage pregnancies",
        "Theme": "Reproductive Health",
        "Definition":"Percentage (%) of women 15 to 19 years old who had given birth or were pregnant with their first child over the full sample of women aged 15 to 49",
        "Unit": "per cent",
        "Denominator": "women aged 15 to 49",
        "Statement":"of women aged 15 to 19 years old (over the full sample of women aged 15 to 49) had given birth or were pregnant with their first child",
        "Proportional": false,
    },
    "U_Pregn": {
        "Indicator":"Unwanted births",
        "Theme":"Reproductive Health",
        "Definition":"Percentage (%) of births that were either wanted earlier or later than occurred (mistimed) or not wanted at all",
        "Unit": "per cent",
        "Denominator": "",
        "Statement":"of births were either wanted earlier or later than occurred (mistimed) or not wanted at all",
        "Proportional": false,
    },
    "Anaemia": {
        "Indicator":"Prevalence of anaemia ",
        "Theme":"Reproductive Health",
        "Definition":"Percentage of women age 15 to 49 with mild, moderate or severe anaemia or with any anaemia",
        "Unit": "per cent",
        "Denominator":"women interviewed (check with DHS if it's all women 15 ot 49 or a subsample of women who were asked about anaemia",
        "Statement":"of women age 15 to 49 had mild, moderate or severe anaemia",
        "Proportional":false,
    },
    "ANC_4plus": {
        "Indicator":"Antenatal care (4+ visits)",
        "Theme":"Reproductive Health",
        "Definition":"Percentage (%) of women with a birth in the last 5 years, who had at least 4 antenatal care visits for most recent birth",
        "Unit": "per cent",
        "Denominator":"women who had a live birth in the five (or three) years preceding the survey",
        "Statement":"of women with a birth in the last 5 years had at least 4 antenatal care visits for most recent birth",
        "Proportional":true,
    },
    "ANC_blood": {
        "Indicator":"Antenatal care (blood screening)",
        "Theme":"Reproductive Health",
        "Definition":"Percentage (%) of women with a live birth in the five years preceding the survey who received antenatal care (ANC) for the most recent birth with blood sample taken.",
        "Unit": "per cent",
        "Denominator":"women who had a live birth in the five (or three) years preceding the survey and received ANC",
        "Statement":"of women with a live birth in the last five years received antenatal care (ANC) for the most recent birth with blood sample taken",
        "Proportional":true,
    },
    "ANC_suppl": {
        "Indicator":"Antenatal care (supplements)",
        "Theme":"Reproductive Health",
        "Definition":"Among women who received antenatal care for their most recent live birth in the past 5 years, the percentage (%) that received supplements (IFA, MMS).",
        "Unit": "per cent",
        "Denominator":"women who had a live birth in the five (or three) years preceding the survey",
        "Statement":"of women who received antenatal care and supplements (IFA, MMS) for their most recent live birth in the past 5 years",
        "Proportional":true,
    },
    "ANC_timing": {
        "Indicator":"Antenatal care (timing)",
        "Theme":"Reproductive Health",
        "Definition":"Percentage (%) of women who had a live birth in the five years preceding the survey whose first antenatal care visit was at less than 4 months ",
        "Unit": "per cent",
        "Denominator": "",
        "Statement":"of women had the first antenatal care visit at less than 4 months during their pregnancies",
        "Proportional": true,
    },
    "ANC_urine": {
        "Indicator":"Antenatal care (urine screening)",
        "Theme":"Reproductive Health",
        "Definition":"Percentage (%) of women with a live birth in the five years preceding the survey who received antenatal care (ANC) for the most recent birth with urine sample taken.",
        "Unit": "per cent",
        "Denominator":"women who had a live birth in the five (or three) years preceding the survey and received ANC",
        "Statement":"of women with a live birth in the last five years received antenatal care (ANC) for the most recent birth with urine sample taken.",
        "Proportional":true,
    },
    "Breastfeed": {
        "Indicator":"Exclusive breastfeeding",
        "Theme":"Nutrition",
        "Definition":"Percentage (%) of youngest children under 6 months who were living with their mother who were exclusively breastfed under 6 months of age",
        "Unit": "per cent",
        "Denominator":"children under age 6 months",
        "Statement":"of youngest children under 6 months were living with their mother who were exclusively breastfed under 6 months of age",
        "Proportional":true,
    },
    "C_Prev": {
        "Indicator":"Modern contraceptive use",
        "Theme":"Reproductive Health",
        "Definition":"Percentage (%) of currently married or in union women currently using any modern method of contraception",
        "Unit": "per cent",
        "Denominator":"all women",
        "Statement":"of married or in union women currently use any modern method of contraception",
        "Proportional":true,
    },
    "Child_m": {
        "Indicator":"Child marriage",
        "Theme":"Child Protection",
        "Definition":"Percentage (%) of women aged 20 to 24 years who were married or in a union before age 18. ",
        "Unit": "per cent",
        "Denominator":"women aged 15 to 49",
        "Statement":"of women aged 20 to 24 years were married or in union before age 18. ",
        "Proportional":false,
    },
    "Labour_fem": {
        "Indicator":"Female labour force participation",
        "Theme":"Livelihoods",
        "Definition":"Percentage (%) of currently married or in union women employed in the 12 months preceding the survey. The indicator includes those who worked in the past year, those who were currently working and those who have a job but were on leave over the last 7 days.",
        "Unit": "per cent",
        "Denominator":"women currently in a union",
        "Statement":"of currently married or in union women were employed",
        "Proportional":true,
    },
    "NAR_prim": {
        "Indicator":"Net primary school attendance rate",
        "Theme":"Education",
        "Definition":"Percentage (%) of children of official primary school-age who were enrolled in primary education",
        "Unit": "per cent",
        "Denominator":"de facto household population of primary school age (this varies by Country)",
        "Statement":"of children of official primary school age were enrolled in primary education",
        "Proportional": true,
    },
    "NAR_sec": {
        "Indicator":"Net secondary school attendance rate",
        "Theme":"Education",
        "Definition":"Percentage (%) of children of official secondary school-age who were enrolled in secondary education",
        "Unit": "per cent",
        "Denominator":"de facto household population of secondary school age (this varies by Country)",
        "Statement":"Percentage (%) of children of official secondary school-age who were enrolled in secondary education",
        "Proportional": true,
    },
    "Stunting": {
        "Indicator":"Prevalence of stunting",
        "Theme":"Nutrition",
        "Definition":"Percentage (%) of children under age five years stunted (below  to 2\u2009SD of height-for-age according to the World Health Organisation\u2019s (WHO) standard).",
        "Unit": "per cent",
        "Denominator":"children under age five",
        "Statement":"of children under age five years were stunted",
        "Proportional":false,    
    },
    "Wasting": {
        "Indicator":"Prevalence of wasting",
        "Theme":"Nutrition",
        "Definition":"Percentage (%) of children wasted (below  to 2\u2009SD of weight-for-height according to the World Health Organisation\u2019s (WHO) standard).",
        "Unit": "per cent",
        "Denominator":"children",
        "Statement":"of children were wasted",
        "Proportional":false,
    },
    "Wash_sanit": {
        "Indicator":"WASH coverage (sanitation)",
        "Theme":"WASH",
        "Definition":"Percentage (%) of the population with access to improved toilet facilities (Improved sanitation facilities include flush toilet, pit latrine (with at least a slab) or a composting toilet)",
        "Unit": "per cent",
        "Denominator":"household level",
        "Statement":"of the population had access to improved toilet facilities",
        "Proportional": true,
    },
    "Wash_water": {
        "Indicator":"WASH coverage (water)",
        "Theme":"WASH",
        "Definition":"Percentage (%) of the population with access to improved drinking water (Improved sources of drinking water include water piped into dwelling or yard/plot, to a neighbour, access to a public tap/standpipe, tube well or borehole, protected well, protected spring, rainwater, tanker truck, cart with small tank and bottled water)",
        "Unit": "per cent",
        "Denominator":"household level",
        "Statement":"of the population had access to improved drinking water",
        "Proportional": true,
    },
    "NMR": {
        "Indicator":"Neonatal mortality rate",
        "Theme":"Child Health",
        "Definition":"Probability (expressedper 1,000 live births) of a child dying before reaching the age of 1 month over a 5-year reference period",
        "Unit": "per 1,000 live births",
        "Denominator":"admin unit level",
        "Statement":"were dying before reaching the age of 1 month over a 5-year reference period",
        "Proportional":false,
    },
    "Unsafe_Ab": {
        "Indicator":"Unsafe abortions ",
        "Theme":"Reproductive Health",
        "Definition":"Percentage (%) of pregnancies terminated either by persons lacking the necessary skills or in an environment that does not conform to minimal medical standards or both ",
        "Unit": "per cent",
        "Denominator": "",
        "Statement":"of pregnancies  were terminated either by persons lacking the necessary skills or in an environment that does not conform to minimal medical standards",
        "Proportional": false,
    },
    "U5": {
        "Indicator":"Under five mortality rate",
        "Theme":"Child Health",
        "Definition":"",
        "Unit": "",
        "Denominator": "admin unit level",
        "Statement":"",
        "Proportional": false,
    },
    "CHMR": {
        "Indicator":"Child mortality rate",
        "Theme":"Child Health",
        "Definition":"Probability (expressedper 1,000 children surviving their first birthday) of a child dying on or after their first birthday but before reaching the age of five years over a 5-year reference period.",
        "Unit": "per 1,000 children surviving to their first birthday",
        "Denominator": "admin unit level",
        "Statement":"were dying on or after their first birthday but before reaching the age of five years",
        "Proportional": false,
    },
    "Lab_child": {
        "Indicator":"Prevalence of child workers",
        "Theme":"Child Protection",
        "Definition":"Percentage (%) of children engaged in any form of work (both marginal and full-time) that may compromise their physical, mental, social or educational development. The official definition of child age may vary between countries.",
        "Unit": "per cent",
        "Denominator": "",
        "Statement":"of children engaged in any form of work that may compromise their physical, mental, social or educational development",
        "Proportional": false,
    },
    "Stillbirth": {
        "Indicator":"Still birth rate",
        "Theme":"Child Health",
        "Definition":"Number of pregnancies that lasted seven or more months and terminated in a foetal death in the five years preceding the survey per 1,000 births (stillbirths plus the number of live births in the five years preceding the survey)",
        "Unit": "per 1,000 births",
        "Denominator": "admin unit level",
        "Statement":"were associated with pregnancies that lasted seven or more months and terminated in a foetal death",
        "Proportional": false,
    },
    "NTDs_helm": {
        "Indicator":"NTDs: Soil-transmitted helminth infections",
        "Theme":"Neglected Tropical Diseases",
        "Definition":"Prevalence of soil-transmitted helminth infection in the population",
        "Unit": "per 100,000 people",
        "Denominator": "admin unit level",
        "Statement":"got soil-transmitted helminth infection",
        "Proportional": false,
    },
    "NTDs_schi": {
        "Indicator":"NTDs: Schistosomiasis",
        "Theme":"Neglected Tropical Diseases",
        "Definition":"Prevalence of schistosomiasis infection in the population",
        "Unit": "per 100,000 people",
        "Denominator": "admin unit level",
        "Statement":"got schistosomiasis infection",
        "Proportional": false,
    },
    "NTDs_fil": {
        "Indicator":"NTDs: Lymphatic filariasis infections",
        "Theme":"Neglected Tropical Diseases",
        "Definition":"Prevalence of lymphatic filariasis infection in the population",
        "Unit": "per 100,000 people",
        "Denominator": "admin unit level",
        "Statement":"got lymphatic filariasis infection",
        "Proportional": false,
    },
    "NTDs_oncho": {
        "Indicator":"NTDs: Onchocerciasis infections",
        "Theme":"Neglected Tropical Diseases",
        "Definition":"Prevalence of onchocerciasis infection in the population",
        "Unit": "per 100,000 people",
        "Denominator": "admin unit level",
        "Statement":"got onchocerciasis infection",
        "Proportional": false,
    },
}

export const StateStyle = () => {
    return {
        weight: 1,
        opacity: 0.5,
        color: 'black',
        fillOpacity: 0,
    }
}

export const StateStyle2 = () => {
  return {
      weight: 3,
      opacity: 1,
      color: 'black',
      fillOpacity: 0,
  }
}

export const DistrictStyle = () => {
  return {
      weight: 0.8,
      opacity: 1,
      color: '#000000',
      fillOpacity: 0,
  }
}

export const colormaps = {
    "ciff_divergent":{"0":"#E90051","1":"#ED2641","2":"#F24C31","3":"#F67120","4":"#FB9710","5":"#FFBD00","6":"#F5C029","7":"#ECC352","8":"#E2C67A","9":"#D9C9A3","10":"#CFCCCC","11":"#AAC2C6","12":"#86B9BF","13":"#61AFB9","14":"#3DA6B2","15":"#189CAC","16":"#2B8BAC","17":"#3E7AAC","18":"#5068AD","19":"#6357AD"},
    "CIFF20":{"0":"#73B2FF","1":"#738FE5","2":"#746DCB","3":"#754BB1","4":"#5D5CAC","5":"#3F77AC","6":"#2192AC","7":"#48B0AF","8":"#91D0B5","9":"#DAEFBB","10":"#FFF4A0","11":"#FFDF64","12":"#FFCA28","13":"#FCA908","14":"#F56D22","15":"#EE313B","16":"#EA0956","17":"#F14178","18":"#F87A99","19":"#FFB3BB"},
    "CIFF20_r":{"0":"#FFB3BB","1":"#F87A99","2":"#F14178","3":"#EA0956","4":"#EE313B","5":"#F56D22","6":"#FCA908","7":"#FFCA28","8":"#FFDF64","9":"#FFF4A0","10":"#DAEFBB","11":"#91D0B5","12":"#48B0AF","13":"#2192AC","14":"#3F77AC","15":"#5D5CAC","16":"#754BB1","17":"#746DCB","18":"#738FE5","19":"#73B2FF"}
}

let pos = []
let neg = []
Object.keys(indicatorDef).forEach((key) => {
    let item = indicatorDef[key]
    if (item.Proportional) {pos.push(key)} else {neg.push(key)}
})

export const pIndicator = pos
export const nIndicator = neg

export const probOption = {
    'Show Improvement': {
      'posA': {'label':'any (>0%)', 'limit':0},
      'posB': {'label':'likely (>90%)', 'limit':90},
      'posC': {'label':'highly likely (>95%)', 'limit':95},
    },
    'Show Worsening': {
      'negA': {'label':'any (>0%)', 'limit':0},
      'negB': {'label':'likely (>90%)', 'limit':90},
      'negC': {'label':'highly likely (>95%)', 'limit':95},
    }
}
  