<h5>For indicators where an increase in the value means improvement over time</h5>
<p>
    An area presenting the smallest increase (or a decrease in value) over time of the selected indicator is classified as being <i>the least performing</i>. An area presenting the highest increase over time of the selected indicator is classified as being <i>the highest performing</i>.
</p>

<h5>For indicators where a decrease in the value means improvement over time</h5>
<p>
    An area presenting the highest decrease over time of the selected indicator is classified as being <i>the highest performing</i>. An area presenting the smallest decrease over time of the selected indicator (or an increase in value) is classified as being <i>the least performing</i>.
</p>