<p>
This web application presents a summary of the family health conditions at subnational level. Multiple indicators are presented in map, chart, and tabulated form.
</p>

<h5>Methods</h5>
<p>The estimates presented on this portal are the result of a methodological approach for estimating high resolution maps and there might be deviations from aggregated measures published elsewhere.</p>
<p>For more information please refer to <a href="#pezzulo">Pezzulo <i>et al.</i> (2023)</a>.

<h5>Disclaimer</h5>
<p>Maps used on this website are for general illustration only, and are not intended to be used for reference purposes.</p>
<p>The representation of political boundaries does not necessarily reflect the organization's view on the legal status of a country or territory.</p>

<h5>Acknowledgement</h5>
<ul>
    <li>
        <b>Administrative Boundary of India:</b> Ministry of Science and Technology, Government of India. Survey of India. Online Maps Portal. Administrative Boundary Database (<a href='https://onlinemaps.surveyofindia.gov.in/Digital_Product_Show.aspx' target='_blank'>OVSF/1M/7</a>).
    </li>
    <li id="nfhs4">
        <b>NFHS-4 data:</b> International Institute for Population Sciences (IIPS) and ICF. 2017. National Family Health Survey (NFHS-4), 2015-16: India. Mumbai: IIPS.
    </li>
    <li id="nfhs5">
        <b>NFHS-5 data:</b> International Institute for Population Sciences (IIPS) and ICF. 2021. National Family Health Survey (NFHS-5), India, 2019-21: India. Mumbai: IIPS.
    </li>
</ul>

<h5>References</h5>
<p>
<ul>
    <li id="pezzulo">
        Pezzulo, C., Tejedor-Garavito, N., Chan, H.M.T. et al. A subnational reproductive, maternal, newborn, child, and adolescent health and development atlas of India. Sci Data 10, 86 (2023). (<a href="https://doi.org/10.1038/s41597-023-01961-2">DOI:10.1038/s41597-023-01961-2</a>).
    </li>
</ul>
</p>