<div class='row p-0 m-0'>
<div class='col-6'>
<ol>
    <li>Select a country and indicator to display. Subnational map associated to the indicator will be displayed on the left.</li>
    <li>By default, indicator value from the round 1 survey is displayed on the map.
        <ul>
            <li>Click <i class="fa fa-circle"></i> to see the value from the round 2 survey.</li>
            <li>Click <i class="fa fa-clone"></i> to see the difference between the values from two rounds.</li>
        </ul>
    </li>
    <li>Click <i class="fa fa-plus-circle"></i> or <i class="fa fa-minus-circle"></i> to zoom-in or zoom-out the map.</li>
    <li>Click <i class="fa fa-arrow-circle-left"></i> to reset the map view.
    <li>Select an administrative unit from the list provided. Selection can also be done by clicking any region on the map.</li>
    <li>Chart and tabulated data for the selected unit is displayed on the right. The data can be sorted according to the sub-unit name or the indicator values.</li>
    <li>The aggregated values of all indicators from the selected unit can also be seen on the panel.</li>
</ol>
</div>
<div class='col-6'>
    <img src='./fig/guide_1.PNG' alt='Guide 1' style='width:100%'>
    <img src='./fig/guide_2.PNG' alt='Guide 2' style='width:100%'>
    <img src='./fig/guide_3.PNG' alt='Guide 3' style='width:100%'>
</div>
</div>