<p>
    Irrespective of the direction of each indicator, the legend displays a better condition (improvement over time when looking at time change) in blue, and a worse condition (worsening over time when looking at time change) in red. For example, 
    <ul>
    <li> increasing value meaning better condition like % of contraceptive prevalence
    <li> increasing value meaning worse condition like % of low birth weight
    </ul>
</p>